// Мок-данные для артистов и альбомов

/** @typedef {import('./types').Artist} Artist */
/** @typedef {import('./types').Album} Album */

/** @type {Artist[]} */
const artists = [
  {
    id: 'artist_1',
    name: 'Ramones',
    slug: 'ramones',
    bio: 'American punk rock band formed in 1974, known for loud, fast songs.',
    imageUrl: '/assets/covers/artist%201.jpg',
    country: 'USA',
    website: 'https://www.ramones.com/',
    genres: ['Punk Rock'],
    isActive: true,
    createdAt: new Date('2020-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'artist_2',
    name: 'Yelawolf',
    slug: 'yelawolf',
    bio: 'Yelawolf (настоящее имя — Майкл Уэйн Эта, англ. Michael Wayne Atha) — американский рэпер, музыкант. Родился 30 декабря 1979 года в Гадсдене, Алабама. Работает в жанрах хип-хоп, кантри, кантри-рэп, рэп-рок.',
    imageUrl: '/assets/covers/artist%202.jpeg',
    country: 'USA',
    website: 'https://www.yelawolf.com/',
    genres: ['Hip-Hop', 'Country', 'Country-Rap', 'Rap-Rock'],
    isActive: true,
    createdAt: new Date('2021-05-10T00:00:00.000Z'),
    updatedAt: new Date('2024-03-15T00:00:00.000Z'),
  },
  {
    id: 'artist_3',
    name: 'Machine Gun Kelly',
    slug: 'machine-gun-kelly',
    bio: 'Machine Gun Kelly — Колсон Бейкер (англ. Colson Baker; 22 апреля 1990, Хьюстон, Техас), более известный под псевдонимом Machine Gun Kelly. американский рэпер, рок-музыкант, певец, актёр. Первоначально писал в жанрах «хип-хоп» и «альтернативный хип-хоп», иногда добавляя рок-элементы. После дисса на Эминема выпустил EP Binge и альбом Hotel Diablo, после чего полностью перешёл на рок-звучание в альбоме Tickets to My Downfall.',
    imageUrl: '/assets/covers/artist%203.jpg',
    country: 'USA',
    website: 'https://www.machinegunkelly.com/',
    genres: ['Rap', 'Rap-Rock', 'Hip-Hop'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'artist_4',
    name: 'Medium Build',
    slug: 'medium-build',
    bio: 'Николас Карпентер, известный под сценическим псевдонимом Medium Build, — американский певец и автор песен. Он выпустил пять студийных альбомов и подписал контракт с лейблами Slowplay / Island Records.',
    imageUrl: '/assets/covers/artist%204.jpg',
    country: 'USA, Anchorage, Alaska',
    website: 'https://www.mediumbuildmusic.com/',
    genres: ['Rock', 'Country', 'Indie Rock'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'), 
  },
  {
    id: 'artist_5',
    name: 'Ozzy Osbourne',
    slug: 'ozzy-osbourne',
    bio: 'Оззи Осборн (англ. Ozzy Osbourne; настоящее имя — Джон Майкл Осборн, англ. John Michael Osbourne) — британский музыкант, автор песен, актёр. Основатель рок-группы Black Sabbath, The Priests, в которой выступал в 1979—1980 годах. Осборн был известен своими длинными волосами, большим количеством татуировок и почерком, называемым «Оззи-стиль», а также за свою репутацию как «Король рок-н-ролла».',
    imageUrl: '/assets/covers/artist%205.jpg',
    country: 'UK',
    website: 'www.ozzy.com',
    genres: ['Rock', 'Metal', 'Heavy Metal', 'Rock-n-Roll'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'artist_6',
    name: 'Highly Suspect',
    slug: 'highly-suspect',
    bio: 'Highly Suspect — американская рок‑группа, основанная в 2009 году в Кейп‑Коде (Массачусетс) Джонни Стивенсом, Ричем Мейером и Райаном Мейером, получившая две номинации на «Грэмми» за дебютный альбом Mister Asylum (2015) и выпустившая ряд успешных релизов, включая The Boy Who Died Wolf (2016), MCID (2019), The Midnight Demon Club (2022) и As Above, So Below (2024).',
    imageUrl: '/assets/covers/artist%206.jpg',
    country: 'USA, Cape Cod, Massachusetts',
    website: 'https://highlysuspect.net/',
    genres: ['Rock', 'Metal', 'Heavy Metal', 'Rock-n-Roll'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'artist_7',
    name: 'Jack White',
    slug: 'jack-white',
    bio: 'Джек Уайт (род. 9 июля 1975, Детройт, США) — американский рок‑музыкант, певец, гитарист, автор песен, продюсер и актёр, прославившийся как основатель и участник группы The White Stripes, позднее создавший группы The Raconteurs и The Dead Weather, выпустивший успешные сольные альбомы (Blunderbuss, Lazaretto, Boarding House Reach), обладатель двенадцати премий «Грэмми» и основатель звукозаписывающего лейбла Third Man Records.',
    imageUrl: '/assets/covers/artist%207.jpg',
    country: 'USA, Detroit, Michigan',
    website: 'https://jackwhiteiii.com/',
    genres: ['Rock', 'Blues', 'Rock-n-Roll'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'artist_8',
    name: 'Lil Wayne',
    slug: 'lil-wayne',
    bio: 'Дуэйн Майкл Картер‑младший (более известный как Lil Wayne; род. 27 сентября 1982, Новый Орлеан, Луизиана) — американский рэпер, автор песен, музыкальный менеджер и предприниматель, начавший карьеру в 9 лет на лейбле Cash Money, участник группы Hot Boys, основатель лейбла Young Money, обладатель четырёх премий «Грэмми», один из самых продаваемых хип‑хоп‑исполнителей в истории.',
    imageUrl: '/assets/covers/artist%208.jpg',
    country: 'USA, New Orleans, Louisiana',
    website: 'https://lilwayne.com/',
    genres: ['Rap', 'Hip-Hop', 'Rap-Rock'],
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
];

/** @type {Album[]} */
const albums = [
  {
    id: 'album_1',
    title: 'Ramones',
    slug: 'ramones',
    artistId: 'artist_1',
    releaseDate: new Date('1976-01-01T00:00:00.000Z'),
    label: 'Sire Records',
    catalogNumber: 'AR-001',
    description: 'Debut LP with smooth night-time Punk Rock vibes.',
    coverImageUrl: '/assets/covers/artist%201%20album%201.jpg',
    genres: ['Punk Rock'],
    trackCount: 14,
    duration: 42 * 60,
    isCompilation: false,
    createdAt: new Date('2022-05-01T00:00:00.000Z'),
    updatedAt: new Date('2022-06-01T00:00:00.000Z'),
  },
  {
    id: 'album_2',
    title: 'Leave Home',
    slug: 'leave-home',
    artistId: 'artist_1',
    releaseDate: new Date('1977-01-01T00:00:00.000Z'),
    label: 'Sire Records',
    catalogNumber: 'MC-010',
    description: 'Second LP with more Punk Rock vibes.',
    coverImageUrl: '/assets/covers/artist%201%20album%202.jpg',
    genres: ['Punk Rock'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_3',
    title: 'Rocket to Russia',
    slug: 'rocket-to-russia',
    artistId: 'artist_1',
    releaseDate: new Date('1977-01-01T00:00:00.000Z'),
    label: 'Sire Records',
    catalogNumber: 'MC-010',
    description: 'Third LP with more Punk Rock vibes.',
    coverImageUrl: '/assets/covers/artist%201%20album%203.jpg',
    genres: ['Punk Rock'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_3',
    title: 'Road to Ruin',
    slug: 'road-to-ruin',
    artistId: 'artist_1',
    releaseDate: new Date('1978-01-01T00:00:00.000Z'),
    label: 'Sire Records',
    catalogNumber: 'MC-010',
    description: 'Fourth LP with more Punk Rock vibes.',
    coverImageUrl: '/assets/covers/artist%201%20album%204.jpg',
    genres: ['Punk Rock'],
    trackCount: 12,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_1',
    title: 'Creek Water',
    slug: 'creek-water',
    artistId: 'artist_2',
    releaseDate: new Date('2005-01-01T00:00:00.000Z'),
    label: 'Self-released',
    catalogNumber: 'MC-010',
    description: 'First LP with  Country Hip-Hop vibes.',
    coverImageUrl: '/assets/covers/artist%202%20album%201.jpg',
    genres: ['Hip-Hop'],
    trackCount: 16,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_2',
    title: 'Radioactive',
    slug: 'radioactive',
    artistId: 'artist_2',
    releaseDate: new Date('2011-01-01T00:00:00.000Z'),
    label: 'Shady Records',
    catalogNumber: 'MC-010',
    description: 'First LP with  Country Hip-Hop vibes on Shady Records.',
    coverImageUrl: '/assets/covers/artist%202%20album%202.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock'],
    trackCount: 18,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_3',
    title: 'Love Story',
    slug: 'love-story',
    artistId: 'artist_2',
    releaseDate: new Date('2015-01-01T00:00:00.000Z'),
    label: 'Shady Records',
    catalogNumber: 'MC-010',
    description: 'Love Story is the third studio album by American rapper Yelawolf. It was released on April 21, 2015, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%203.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 18,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_4',
    title: 'Trial by Fire',
    slug: 'trial-by-fire',
    artistId: 'artist_2',
    releaseDate: new Date('2017-01-01T00:00:00.000Z'),
    label: 'Shady Records',
    catalogNumber: 'MC-010',
    description: 'Trial by Fire is the fourth studio album by American rapper Yelawolf. It was released on November 10, 2017, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%204.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_5',
    title: 'Trunk Muzic 3',
    slug: 'trunk-muzic-3',
    artistId: 'artist_2',
    releaseDate: new Date('2019-01-01T00:00:00.000Z'),
    label: 'Shady Records',
    catalogNumber: 'MC-010',
    description: 'Trunk Muzic 3 is the fifth studio album by American rapper Yelawolf. It was released on October 11, 2019, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%205.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_6',
    title: 'Ghetto Cowboy',
    slug: 'ghetto-cowboy',
    artistId: 'artist_2',
    releaseDate: new Date('2019-01-01T00:00:00.000Z'),
    label: 'SLumerican Records',
    catalogNumber: 'MC-010',
    description: 'Ghetto Cowboy is the sixth studio album by American rapper Yelawolf. It was released on October 11, 2019, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%206.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_7',
    title: 'Mud Mouth',
    slug: 'mud-mouth',
    artistId: 'artist_2',
    releaseDate: new Date('2021-01-01T00:00:00.000Z'),
    label: 'SLumerican Records',
    catalogNumber: 'MC-010',
    description: 'Mud Mouth is the seventh studio album by American rapper Yelawolf. It was released on October 11, 2021, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%207.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 14,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_8',
    title: 'War Story',
    slug: 'war-story',
    artistId: 'artist_2',
    releaseDate: new Date('2024-01-01T00:00:00.000Z'),
    label: 'SLumerican Records',
    catalogNumber: 'MC-010',
    description: 'War Story is the eighth studio album by American rapper Yelawolf. It was released on October 11, 2023, by Slumerican, Shady Records, and Interscope Records. The album was described by Yelawolf as a more passionate album than his debut album. Recording process took place primarily in Nashville, Tennessee from 2012 to 2015.',
    coverImageUrl: '/assets/covers/artist%202%20album%208.jpg',
    genres: ['Hip-Hop', 'Rap', 'Rap-Rock', 'Country', 'Country-Rap'],
    trackCount: 25,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_1',
    title: 'Lace Up',
    slug: 'lace-up',
    artistId: 'artist_3',
    releaseDate: new Date('2012-01-01T00:00:00.000Z'),
    label: 'Bad Boy Records',
    catalogNumber: 'MC-010',
    description: 'дебютный студийный альбом американского рэпера Machine Gun Kelly, выпущенный 9 октября 2012 года на лейблах Bad Boy Records и Interscope Records.[1]',
    coverImageUrl: '/assets/covers/artist%203%20album1.jpg',
    genres: ['Hip-Hop', 'Rap',],
    trackCount: 13,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },
  {
    id: 'album_2',
    title: 'General Admission',
    slug: 'general-admission',
    artistId: 'artist_3',
    releaseDate: new Date('2015-01-01T00:00:00.000Z'),
    label: 'Bad Boy Records',
    catalogNumber: 'MC-010',
    description: 'Второй студийный альбом американского рэпера Machine Gun Kelly, выпущенный 16 октября 2015 года лейблами EST 19XX, Bad Boy и Interscope Records[1][2][3][4]. Альбом был поддержан двумя синглами: «Till I Die» и «A Little More» с участием Виктории Моне.',
    coverImageUrl: '/assets/covers/artist%203%20album%202.jpg',
    genres: ['Hip-Hop', 'Rap',],
    trackCount: 16,
    duration: 48 * 60,
    isCompilation: false,
    createdAt: new Date('2023-02-10T00:00:00.000Z'),
    updatedAt: new Date('2023-03-15T00:00:00.000Z'),
  },

  {
    id: 'album_3',
  title: 'Bloom',
  slug: 'bloom',
  artistId: 'artist_3',
  releaseDate: new Date('2017-01-01T00:00:00.000Z'),
  label: 'Bad Boy Records',
  catalogNumber: 'MC-010',
  description: 'Третий студийный альбом американского рэпера Machine Gun Kelly, выпущенный 21 апреля 2017 года на лейблах Bad Boy Records и Interscope Records[1][2]. Альбом был поддержан синглами «Wanna Know» и «Home».',
  coverImageUrl: '/assets/covers/artist%203%20album%203.jpg',
  genres: ['Hip-Hop', 'Rap',],
  trackCount: 15,
  duration: 48 * 60,
  isCompilation: false,
  createdAt: new Date('2023-02-10T00:00:00.000Z'),
  updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
{
  id: 'album_4',
title: 'Binge',
slug: 'binge',
artistId: 'artist_3',
releaseDate: new Date('2018-01-01T00:00:00.000Z'),
label: 'Bad Boy Records',
catalogNumber: 'MC-010',
description: 'EP американского рэпера Machine Gun Kelly, выпущенный 21 сентября 2018 года на лейблах Bad Boy Records и Interscope Records. Альбом был поддержан синглами «Bloody Valentine» и «Home».',
coverImageUrl: '/assets/covers/artist%203%20album%204.jpg',
genres: ['Hip-Hop', 'Rap',],
trackCount: 9,
duration: 48 * 60,
isCompilation: false,
createdAt: new Date('2023-02-10T00:00:00.000Z'),
updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
{
  id: 'album_5',
title: 'Hotel Diablo',
slug: 'hotel-diablo',
artistId: 'artist_3',
releaseDate: new Date('2019-01-01T00:00:00.000Z'),
label: 'Bad Boy Records',
catalogNumber: 'MC-010',
description: 'Студийный альбом американского рэпера Machine Gun Kelly, выпущенный 27 сентября 2019 года на лейблах Bad Boy Records и Interscope Records. Альбом был поддержан синглами «Bloody Valentine» и «Home».',
coverImageUrl: '/assets/covers/artist3album5.jpg',
genres: ['Hip-Hop', 'Rap',],
trackCount: 14,
duration: 48 * 60,
isCompilation: false,
createdAt: new Date('2023-02-10T00:00:00.000Z'),
updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
{
  id: 'album_6',
title: 'Tickets to My Downfall',
slug: 'tickets-to-my-downfall',
artistId: 'artist_3',
releaseDate: new Date('2020-01-01T00:00:00.000Z'),
label: 'Bad Boy Records',
catalogNumber: 'MC-010',
description: 'Пятый студийный альбом американского рэпера Machine Gun Kelly[5]. Альбом был выпущен 25 сентября 2020 года на лейблах Interscope и Bad Boy Records[6].ийный альбом американского рэпера Machine Gun Kelly, выпущенный 27 сентября 2019 года на лейблах Bad Boy Records и Interscope Records. Альбом был поддержан синглами «Bloody Valentine» и «Home».',
coverImageUrl: '/assets/covers/artist3album%206.jpg',
genres: ['Hip-Hop', 'Rap',],
trackCount: 15,
duration: 48 * 60,
isCompilation: false,
createdAt: new Date('2023-02-10T00:00:00.000Z'),
updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
{
  id: 'album_7',
title: 'Mainstream Sellout',
slug: 'mainstream-sellout',
artistId: 'artist_3',
releaseDate: new Date('2022-01-01T00:00:00.000Z'),
label: 'Bad Boy Records',
catalogNumber: 'MC-010',
description: 'шестой студийный альбом американского музыканта Machine Gun Kelly, выпущенный 25 марта 2022 года на лейблах Bad Boy Records и Interscope Records. Это его второй совместный проект с барабанщиком и продюсером Трэвисом Баркером после Tickets to My Downfall 2020 года.',
coverImageUrl: '/assets/covers/artist3album7.jpg',
genres: ['Hip-Hop', 'Rap',],
trackCount: 16,
duration: 48 * 60,
isCompilation: false,
createdAt: new Date('2023-02-10T00:00:00.000Z'),
updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
{
  id: 'album_8',
title: 'Lost Americana',
slug: 'lost-american',
artistId: 'artist_3',
releaseDate: new Date('2025-01-01T00:00:00.000Z'),
label: 'Bad Boy Records',
catalogNumber: 'MC-010',
description: 'седьмой студийный альбом хип-хоп исполнителя Machine Gun Kelly, выпущенный 8 августа 2025 года лейблом EST 19XX совместно с самим артистом. До выхода альбома вышли 3 сингла, которые также были включены в трек-лист — «cliché», «miss sunshine» и «vampire diaries».',
coverImageUrl: '/assets/covers/artist3album8.jpg',
genres: ['Hip-Hop', 'Rap',],
trackCount: 14,
duration: 48 * 60,
isCompilation: false,
createdAt: new Date('2023-02-10T00:00:00.000Z'),
updatedAt: new Date('2023-03-15T00:00:00.000Z'),
},
];

module.exports = {
  artists,
  albums,
};
